export enum ErrorCodeEnum {
    INVALID_DATA = "INVALID_DATA",
    NOT_FOUND = "NOT_FOUND",
    REFERRAL_CODE_ERROR = "REFERRAL_CODE_ERROR",
    OTP_ERROR = "OTP_ERROR",
    NOT_ENOUGH_XIKASU_TOKENS = "NOT_ENOUGH_XIKASU_TOKENS"
}
